print ("hello git")
print ("metas")
print ("1. soy developer full stack")
print ("este hello 1 sera para cosas dedevelopment")
print ("lo que llevamos es repaso de la configuracion y comandos basicos para crear fihcheros, y moverse en ellos")
print ("tambien hemos aprendido algunos comandos basicos de Git")
print ("update 10.0.0")
print ("update 12.0.1")
