print ("hello git 2")
print ("completar el curso de mouredev")
print ("completar el curso de angela")
print ("completar el curso de meet")
print ("completar mas cursos")
print ("este hello 2 sera para lo de gestoria vehicular")
print ("los 2 coches estan desvielados, ambos ya estan en el mecanico y los motores ya estan en proceso de la rectificadora")
print ("update 10.0.0")
print ("update 12.0.1")
print ("EN GITHUB update 12.0.3")
print ("EN GITHUB update 12.0.4")
print ("EN GITHUB update 12.0.5")
print ("EN GITHUB update 12.0.6")
print ("EN GITHUB update 12.0.7")
print ("EN GITHUB update 12.0.8")
print ("EN GITHUB update 12.0.9")
print ("EN GITHUB update 13.0.0")
print ("EN GITHUB update 13.0.1")
print ("EN GITHUB update 13.0.3")
print ("EN GITHUB update 13.0.4")
print ("EN GITHUB update 13.1.0")
print ("EN GITHUB update PROYECT 13.2.0")
print ("EN GITHUB update HELLO 13.2.0")