print ("hello git")
print ("metas")
print ("1. soy developer full stack")
print ("este hello 1 sera para cosas dedevelopment")
print ("lo que llevamos es repaso de la configuracion y comandos basicos para crear fihcheros, y moverse en ellos")
print ("tambien hemos aprendido algunos comandos basicos de Git")
print ("hasta este punto siento que no avanzo, ya quiero empezar a programar")
