print ("hello git 3")
print ("siguiente paso, ir a chalco ")
print ("contactar grua")
print ("contactar mecanico")
print ("contactar hojalatero")
print ("ir por el auto a zumpango")
print ("los 2 cohes se desvielaron")
print ("repara los 2 coches")
print ("este hello 3 sera apara metas personales")
print ("terminar el audio libro de habitos atomicos")
print ("update 10.0.0")
print ("update 12.0.1")
print ("EN GITHUB update 12.0.3")
print ("EN GITHUB update 12.0.4")
print ("EN GITHUB update 12.0.5")
print ("EN GITHUB update 12.0.6")
print ("EN GITHUB update 12.0.7")
print ("EN GITHUB update 12.0.8")
print ("EN GITHUB update 12.0.9")
print ("EN GITHUB update 13.0.0")
print ("EN GITHUB update 13.0.1")
print ("EN GITHUB update 13.0.3")
print ("EN GITHUB update 13.0.4")
print ("EN GITHUB update 13.1.0")
print ("EN GITHUB update PROYECT 13.2.0")
print ("EN GITHUB update HELLO 13.2.0")
print ("EN GITHUB update PROYECT 13.3.0")
print ("EN GITHUB update HELLO 14.0.0")
print ("EN GITHUB update HELLO 14.0.1")
print ("EN GITHUB update HELLO 14.0.2")
print ("EN GITHUB update HELLO 14.0.3")
print ("EN GITHUB update HELLO 14.0.4")
print ("EN GITHUB update HELLO 14.0.5")

