print ("hello git 2")
print ("completar el curso de mouredev")
print ("completar el curso de angela")
print ("completar el curso de meet")
print ("completar mas cursos")
print ("este hello 2 sera para lo de gestoria vehicular")
print ("los 2 coches estan desvielados, ambos ya estan en el mecanico y los motores ya estan en proceso de la rectificadora")
print ("update 10.0.0")