print ("hello git 2")
print ("completar el curso de mouredev")
print ("completar el curso de angela")
print ("completar el curso de meet")
print ("completar mas cursos")
print ("este hello 2 sera para lo de gestoria vehicular")